// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmRMUUPm3sUtqvd_yeNi3bpOtn5dxClRs',
    appId: '1:783044757243:web:48ee2d87a70ed8f078125e',
    messagingSenderId: '783044757243',
    projectId: 'smart-cabinet-test-7',
    authDomain: 'smart-cabinet-test-7.firebaseapp.com',
    databaseURL: 'https://smart-cabinet-test-7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-cabinet-test-7.firebasestorage.app',
    measurementId: 'G-WDJQ07KJQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MLDRbvJvA1PBsUY9AZHUTXiBc53J444',
    appId: '1:783044757243:android:1e4cbcc6aa58871978125e',
    messagingSenderId: '783044757243',
    projectId: 'smart-cabinet-test-7',
    databaseURL: 'https://smart-cabinet-test-7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-cabinet-test-7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2LgHDXqthCHmJ7Uax5h5IWQzyHc66MJo',
    appId: '1:783044757243:ios:4f120563972ccd1078125e',
    messagingSenderId: '783044757243',
    projectId: 'smart-cabinet-test-7',
    databaseURL: 'https://smart-cabinet-test-7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-cabinet-test-7.firebasestorage.app',
    iosBundleId: 'com.example.smartCabinet',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2LgHDXqthCHmJ7Uax5h5IWQzyHc66MJo',
    appId: '1:783044757243:ios:4f120563972ccd1078125e',
    messagingSenderId: '783044757243',
    projectId: 'smart-cabinet-test-7',
    databaseURL: 'https://smart-cabinet-test-7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-cabinet-test-7.firebasestorage.app',
    iosBundleId: 'com.example.smartCabinet',
  );
}
